[build]
  command = "npm run build"
  publish = ".next"

# This plugin is all you need for Next.js on Netlify.
# It handles routing, SSR, and ISR automatically.
[[plugins]]
  package = "@netlify/plugin-nextjs"
